### PR TITLE
Week 8-13 Progress Update: Mudit Gupta

### PR DESCRIPTION
**Pull request by mg14777**
Added progress report for week 8-11

@wenmogu @craaaa Ready for review

### CODE REVIEW

**Comment by mg14777** [comment]
Added progress report for week 12-13.
@wenmogu @wkurniawan07 @xpdavid Please review if anyone is free. Still awaiting final reviews on some PRs that need to be merged

**Comment by wkurniawan07** [comment]
@mg14777 you need to resolve the merge conflicts.

**Comment by mg14777** [comment]
@wkurniawan07 Ready for review

**Comment by mg14777** [comment]
@wkurniawan07 Please merge this.

**Review by wenmogu — APPROVED** [review]

**Pull request merged**
